- tailwind.config.js
- [ O ] 기능 추가
feat/
tailwind 에서 사용되는 색상을  추출해서 추가했습니다
> Feat : tailwind 커스텀 색상 추출

- src/components/common/Dropdown/index.jsx
- src/components/common/SearchBar/index.jsx
- src/components/common/Tabs/index.jsx
- src/pages/CommunityPage/index.jsx
- src/routes/router.jsx
- (#12) feature/communityTag -> dev
- 
- 커뮤니티 페이지 상단 태그 선택 ui를 구현했습니다.
> feat : 커뮤니티 태그 구현 (#12)

- src/apis/postCreate.js
- src/apis/userFullNameApi.js
- src/pages/CommunityPage/components/Modal.jsx
- src/pages/CommunityPage/components/PostForm.jsx
- src/pages/CommunityPage/components/PostFormModal.jsx
- src/pages/CommunityPage/index.jsx
ex) (#21  ) feat/CommunityPage -> dev
ex) 글 업로드 할 있는 팟업창 추가 및 이미지 부분 주석
> Feat : svg주석 후 업로드(#21)

- src/pages/DetailPage/components/Detail.jsx
- src/pages/DetailPage/components/Map.jsx
- [X ] 기능 추가
ex) (#이슈번호) feat/detailPage -> dev
ex) introduction의 위치를 수정했습니다.
> feat: introduction 위치이동

- src/routes/router.jsx
@jjeongsu feature/newRouter -> main
- 라우터 구조 변경했습니다.
> refactor : router 구조 변경

- src/pages/SearchPage/index.jsx
- [ 0] 기능 추가
ex) (#17 ) feat/search
파일 경로가 잘못되어 수정 하였습니다
> fix: 파일 경로 변경

- src/pages/AddPlanPage/index.jsx
@jjeongsu feature/multistep -> main
add planPage 의 머지 충돌과정에서 기존 코드가 누락되어 있어서 이부분 추가해서 보냅니다.
- @jaeyo03 비짓 제주 검색 기능이 컴포넌트로 분리가 안될상태로 있어서 혹시 요부분  분리해주실수 있을까요? 최종 선택된 장소이름, contentId, 뒤로가기 버튼 눌렀을 때 실행될 onclick이벤트핸들러만 부모(AppPlanPage)에 있으면 됩니다..!
> fix : 충돌과정에서 누락된 코드 복원

- src/apis/supabaseApi.js
jaeyo03 main -> main
postPlanApi에 content_id 추가했습니다
> [FEAT] postPlan에 콘텐츠 id 추가

- src/apis/visitJejuApi.js
- src/pages/CommunityPage/components/PostForm.jsx
- src/pages/CommunityPage/components/PostRender.jsx
- src/pages/CommunityPage/index.jsx
- src/pages/DetailPage/components/Detail.jsx
- src/pages/DetailPage/components/Map.jsx
- src/pages/DetailPage/components/WishlistButton.jsx
- src/pages/DetailPage/index.jsx
- src/redux/slices/user.slice.js
- src/redux/slices/wishlist.slice.js
- src/redux/store.js
- [o ] 기능 추가
ex) (#11 ) feat/detail page -> 
찜하기 버튼용 redux slice를 추가 했습니다. 
userslice에 테스트 케이스 추가하였고 주석처리 해놓았습니다.
찜하기 버튼 supabaseApi와 연결해 보려고 합니다.
> feat: 찜하기 버튼 redux slice 추가, supabaseApi와 연결 중

- src/pages/MyTripPage/components/DayCard.jsx
- src/pages/MyTripPage/components/PlanCard.jsx
- src/pages/MyTripPage/components/PopUpCard.jsx
- src/pages/MyTripPage/index.jsx
main -> main
- 내 일정에서 장소를 눌렀을때 해당 장소를 보여주는 기능을 1차적으로 구현
- propTypes 추가 (제가 쓰는 다른 컴포넌트에서도 이거 차차 적용하겠습니다)
- 컴포넌트에 매개변수가 3,4개 정도 들어간게 있는데 나중에 한번 리팩토링 하겠습니다
> [FEAT] 장소를 표시하는 팝업 컴포넌트 구현

- src/apis/searchApi.js
- src/pages/SearchPage/index.jsx
- src/utils/pagination.js
- [x ] 기능 추가
ex) (#17 ) feat/login -> main
검색화면 페이지네이션 추가했습니다
> Feat : 검색화면 페이지네이션 추가

- src/pages/index.jsx
- src/routes/router.jsx
ex) (#60 ) feat/login -> dev
ex) 라우터 추가 했습니다
> fix : router 경로 추가

- public/icons/line-icon.svg
- src/apis/supabaseApi.js
- src/pages/AddPlanPage/utils/makePlaceObject.js
- src/pages/MyTripPage/components/ChangeTimeModal.jsx
- src/pages/MyTripPage/components/DayButton.jsx
- src/pages/MyTripPage/components/PlanCard.jsx
- src/pages/MyTripPage/components/PopUpCard.jsx
- src/pages/MyTripPage/index.jsx
main -> main
- 일정 삭제, 시간 변경 로직 구현 (복잡하게 구현했는데... 한번 리팩토링 하고 싶습니다)
- 팝업카드 클릭시 호버된 Style 고정 구현
- 일정 시간 변경시 모달 구현
- 일정 업로드시 객체 생성할 때 이미지 속성명 오류 수정
> [FEAT] 일정 삭제, 시간 변경 로직 구현 등

- src/pages/AddPlanPage/components/PlaceCard.jsx
- src/pages/AddPlanPage/components/PlaceTag.jsx
- src/pages/AddTripPage/index.jsx
- src/pages/MyTripPage/components/PopUpCard.jsx
- src/pages/MyTripPage/index.jsx
main -> main
- 이미지 없을 시 빈 이미지 나오도록 구현
- 내 일정 페이지에서 날짜 정보 표시되도록 수정
- 유저 ID 연결
> [FEAT] 날짜 정보 표기 구현 및 유저 ID 연결

- src/components/common/Footer/index.jsx
- src/layouts/AuthLayout.jsx
- src/layouts/DefaultLayout.jsx
- src/pages/DetailPage/components/WishlistButton.jsx
- src/redux/slices/wishlist.slice.js
ex) (#42 ) feat/Footer -> dev
보이는 Footer 구현해봤습니다.
> feat: footer 구현

- src/apis/supabaseApi.js
- src/components/common/Footer/index.jsx
- src/layouts/AuthLayout.jsx
- src/layouts/DefaultLayout.jsx
- src/pages/DetailPage/components/WishlistButton.jsx
- src/redux/slices/wishlist.slice.js
ex) (#11 ) feat/detail page -> dev
찜버튼이 눌려있었다면 기억하기,  삭제되었다면 삭제하는 기능 구현 및 삭제 후 다시 눌리지 않는 버그 해결
> Feature/detail page 찜버튼, 제거 문제 해결

- src/pages/AddPlanPage/components/PlaceTag.jsx
- src/pages/AddPlanPage/components/Search.jsx
- src/pages/MyTripPage/components/PlanCard.jsx
- src/pages/MyTripPage/components/PopUpCard.jsx
- src/pages/MyTripPage/index.jsx
main -> main
- 글자 길이 조절하는 기능 추가
- 일정 추가시 상세페이지 연결
- 일정 sort함수 1차 구현
> [FEAT] 글자 길이 조절 및 일정 시간별 Sort 1차 구현

- src/apis/user.js
- src/pages/MyPage/components/aside/Aside.jsx
- src/pages/MyPage/components/aside/Button.jsx
- src/pages/MyPage/components/aside/ButtonWrapper.jsx
- src/pages/MyPage/components/main/updateUserProfile/UpdateUserSection.jsx
- src/redux/slices/user.slice.js
(#79) @jjeongsu feature/withdraw -> main
- 로그아웃 기능 추가하였습니다.
- 회원탈퇴기능은 버튼은 있는데, 서버에서 관리자계정으로만 가능하도록 구현되어 있습니다. 그래서 굳이 버튼을 삭제하진 않았고 버튼 눌러도 alert창만 뜨게끔 해놨습니다.
- 프로필변경 버튼 누르면 프로필 수정 폼 나오게끔 수정하였습니다.
> [FEAT] 로그아웃

- src/components/common/Footer/index.jsx
- src/layouts/AuthLayout.jsx
- src/layouts/DefaultLayout.jsx
- src/layouts/PlanLayout.jsx
- src/layouts/TripLayout.jsx
- src/pages/DetailPage/components/Detail.jsx
ex) (#42) feat/footer -> style
footer가 밑을 가득 채우게 스타일을 변경했습니다.
패딩을 줘서 안쪽으로 글이 좀 내려오게 만들었습니다.
text color를 조정했습니다.
> style: footer padding, color 수정

- src/components/common/Footer/index.jsx
- src/layouts/AuthLayout.jsx
- src/layouts/DefaultLayout.jsx
- src/layouts/PlanLayout.jsx
- src/layouts/TripLayout.jsx
- src/pages/DetailPage/components/Detail.jsx
ex) (#11 ) style /detail -> style
피그마처럼 위 쪽에 제주 > 성산과 같은 region1cd가 표시되도록 변경했습니다.
검은색 바탕이라 잘 안보이는데 글은 표시되고 있습니다!
> [style] Detail page style 변경

- src/apis/commentCreateApi.js
- src/apis/postCreate.js
- src/pages/CommunityDetailPage/components/CommentForm.jsx
- src/pages/CommunityDetailPage/components/CommentList.jsx
- src/pages/CommunityDetailPage/index.jsx
- src/pages/CommunityPage/components/DetailedPosts.jsx
- src/pages/CommunityPage/components/Pagination.jsx
- src/pages/CommunityPage/components/PostForm.jsx
- src/pages/CommunityPage/components/PostFormModal.jsx
- src/pages/CommunityPage/components/PostRender.jsx
- src/pages/CommunityPage/index.jsx
- src/pages/index.jsx
- src/routes/router.jsx
ex) (#60 ) feat/login -> dev
ex) 커뮤니티 접속시 에러 수정
ex) 커뮤니티 포스트 클릭시 상세페이지로 이동
ex) 커뮤니티 댓글 기능 추가
> Feat : 커뮤니티 상세 페이지 (#60)

- src/pages/CommunityDetailPage/index.jsx
- src/pages/CommunityPage/index.jsx
- src/pages/Homepage/components/Community/CommunityPreviewCard.jsx
- src/pages/Homepage/components/PlanPreview/Calender.jsx
- src/pages/Homepage/components/PlanPreview/RecommandDetailCard.jsx
- src/pages/Homepage/components/PlanPreview/index.jsx
- src/pages/Homepage/components/PlanPreview/recommend.js
- src/pages/Homepage/index.jsx
- src/utils/randomNumber.js
@jjeongsu  feature/mainCommunityLink -> main
- 커뮤니티 프리뷰에서 커뮤니티 상세글로 이동하도록 구현
- 로그인 전에 여행 프리뷰화면이 비어잇는것 같아서, 로그인 혹은 일정 선택전 보여줄 추천 장소카드를 추가하였습니다.
- axios관련 Pr 은 해당 pr이 머지된 이후 합쳐주세요
> [FEAT] 메인페이지 커뮤니티 링크, 추천 장소카드 추가

- src/components/common/Header/index.jsx
- src/constants/mainExamplePlaces.js
- src/pages/Homepage/components/SearchPreview/CategoryButton.jsx
- src/pages/Homepage/components/SearchPreview/MainCard.jsx
- src/pages/Homepage/components/SearchPreview/index.jsx
main -> main
- 카테고리 선택시 장소가 바뀌도록 구현 (숙박, 음식, 축제, 테마여행도 추가,,,?)
- 몇몇 요소 컴포넌트화 (로직 없이 부모에게서만 의존하도록 수정)
- 헤더에서 비로그인시 여행계획 페이지 못 가도록 수정
> [FEAT] 메인페이지 검색 컴포넌트 개발 및 헤더 수정

- src/constants/path.js
- src/hooks/useAuth.js
- src/layouts/index.js
- src/routes/route/AuthRoutes.jsx
- src/routes/route/CommunityRoutes.jsx
- src/routes/route/DetailRoutes.jsx
- src/routes/route/HomeRoutes.jsx
- src/routes/route/MypageRoutes.jsx
- src/routes/route/PlanRoutes.jsx
- src/routes/route/PrivateRoute.jsx
- src/routes/route/PublicRoute.jsx
- src/routes/route/SearchRoutes.jsx
- src/routes/route/TripRoutes.jsx
- src/routes/route/index.js
- src/routes/router.jsx
(#93 ) feature/privateRoute -> main
- 유저 인증 여부에 따라 리다이렉션하는 기능 구현하였습니다.
- 라우터 경로 하드코딩되어 있던것 상수처리 하였습니다.
- mypage
- trip
- plan
=> 로그아웃시 접근하려고 하면 login 페이지로 이동시킨다.
- auth (로그인 회원가입)
=> 로그인시에 접근하려고 하면 홈으로 이동시킨다.
> [FEAT] Private, Public 라우터 추가

- src/constants/mainExamplePlaces.js
- src/pages/DetailPage/index.jsx
- src/pages/Homepage/components/SearchPreview/CategoryButton.jsx
- src/pages/Homepage/components/SearchPreview/index.jsx
main -> main
인페이지용 장소 추가, 상세 페이지 기본 높이 추가
> [FEAT] 메인페이지용 장소 추가, 상세 페이지 기본 높이 추가

- src/apis/commentCreateApi.js
- src/pages/MyPage/components/main/comment/Comment.jsx
- src/pages/MyPage/components/main/comment/CommentSection.jsx
- src/pages/MyPage/components/main/schedule/ScheduleSection.jsx
- src/pages/MyPage/components/main/scrap/ScrapPlaceCard.jsx
- src/pages/MyPage/components/main/scrap/ScrapSection.jsx
- src/routes/route/MypageRoutes.jsx
- src/utils/addressFormat.js
ex) (#15 ) feat/feature-> main
- 마이페이지에서 내가 작성한 댓글을 삭제하는 기능을 추가했습니다.
- 여행 일정 및 스크랩한 장소의 페이지 이동을 구현했습니다.
- 라우터의 오타를 수정했습니다.
- addressFormat 함수의 예외를 찾아 수정했습니다.
> feat 마이페이지 기능 추가

- src/apis/supabaseApi.js
- src/constants/mainExamplePlaces.js
- src/pages/CommunityDetailPage/components/LikeButton.jsx
- src/pages/CommunityDetailPage/index.jsx
- src/pages/Homepage/components/SearchPreview/MainCard.jsx
- src/pages/Homepage/components/SearchPreview/index.jsx
- src/pages/MyPage/components/main/liked/LikedPost.jsx
- src/pages/MyPage/components/main/liked/LikedSection.jsx
main -> main
- 커뮤니티 글 좋아요 누를 시에 수파베이스 API와 연동되도록 구현했습니다
> [FEAT] 수파베이스 커뮤니티 좋아요 구현

- src/apis/channelApi.js
- src/apis/commentCreateApi.js
- src/apis/getUserData.js
- src/apis/likesApi.js
- src/apis/postApi.js
- src/apis/postCreate.js
- src/apis/searchApi.js
- src/apis/userApi.js
- src/components/common/FormInput/FileInput.jsx
- src/hooks/react-query/useFetchUser.js
- src/hooks/react-query/useMutateUser.js
- src/pages/MyPage/components/aside/Aside.jsx
- src/pages/MyPage/components/aside/Profile.jsx
- src/pages/MyPage/components/main/updateUserProfile/UpdateUserSection.jsx
@jjeongsu  applyAxiosInstacne -> main
- axios instance 를 devAPI 인스턴스로 변경하였습니다.
- 다만 이미지 업로드하는 api들은 devAPI로 변경시 헤더타입 충돌로 기본 axios 인스턴스를 사용하도록 하여습니다. 
- 마이페이지 프로필을 더미에서 실제 유저정보를 표시하도록 변경하엿습니다.
- 유저 기능 수정컴포넌트에서 썸네일 이미지가 깨지는 오류가 있어서 수정하였습니다.
> [FEAT] devAPI로 변경 및 마이페이지 프로필 실제 유저정보로 변경

- src/pages/CommunityDetailPage/index.jsx
> fix : 좋아요 길이 수정

- src/apis/followApi.js
- src/pages/CommunityDetailPage/components/CommentDelete.jsx
- src/pages/CommunityDetailPage/components/CommentList.jsx
- src/pages/CommunityDetailPage/components/FollowButton.jsx
- src/pages/CommunityDetailPage/components/Follower.jsx
- src/pages/CommunityDetailPage/components/LikeButton.jsx
- src/pages/CommunityDetailPage/components/ProfileCard.jsx
- src/pages/CommunityDetailPage/index.jsx
- src/pages/CommunityPage/components/PostRender.jsx
- src/pages/CommunityPage/index.jsx
ex) (#106) feat/login -> dev
ex) 팔로우 기능 
ex) 유저별 프로필 카드
> Feat : follow (#106)

- src/apis/postApi.js
- src/apis/postCreate.js
> fix : api 에러 수정

- src/pages/CommunityDetailPage/components/LikeButton.jsx
- src/pages/CommunityDetailPage/index.jsx
> feat : 수파베이스 게시글 좋아요 추가

- src/components/common/Button/index.jsx
- src/constants/mainExamplePlaces.js
- src/index.css
- src/pages/AddTripPage/index.jsx
- src/pages/Homepage/components/SearchPreview/MainCard.jsx
- src/pages/Homepage/components/SearchPreview/WishListButtonMain.jsx
- src/pages/Homepage/components/SearchPreview/index.jsx
- src/pages/MyTripPage/components/ChangeTimeModal.jsx
- src/pages/MyTripPage/components/DayCard.jsx
- src/pages/MyTripPage/components/PopUpCard.jsx
- src/pages/MyTripPage/index.jsx
main -> main
- 담당 페이지 스타일 수정
- 버그 수정
- 메인 페이지에서 좋아요 버튼 모달 추가
- 공통 버튼에 className 추가
> [STYLE] 담당 페이지 CSS 수정

- src/pages/SearchPage/components/DetailCard.jsx
- src/pages/SearchPage/components/DetailMediumCard.jsx
- src/pages/SearchPage/index.jsx
ex) (#17 ) feat/search -> main
1.  UI 수정 완료했습니다 
2. 레이아웃 기능 완성 
3. 버튼을 순간적으로 계속 누르면 에러가 발생...고민중
> Fix : Ui 수정 , 레아아웃 기능 완성

- src/pages/DetailPage/components/Detail.jsx
- src/pages/DetailPage/components/Map.jsx
- src/pages/DetailPage/components/WishlistButton.jsx
ex) (#11 ) feat/DetailPage -> style
1. 제주  > 제주시 의 font size, font color, 문자 간격 조정
2. DummyIndex grid 삭제
3. 지도와 상세 내용 위치 변경 및 상세 내용 위치 조정
4. 지도 크기 키움
> [Style] Detail style 수정

- src/pages/Homepage/components/SearchPreview/MainCard.jsx
- src/pages/Homepage/components/SearchPreview/index.jsx
main -> main
- 회색 배경 수정
- 호버 추가
> [STYLE] 회색 배경 및 호버 추가

- src/pages/DetailPage/components/Detail.jsx
- src/pages/DetailPage/components/DummyIndex.jsx
ex) (#11 ) feat/DetailPage -> style
1. 주소 전화번호 부분 피그마와 달라 다시 구성했습니다.
> [Style] Detail Page 피그마와 동일하게 만들었습니다.

- src/pages/SearchPage/components/Category.jsx
- src/pages/SearchPage/components/DetailSmallCard.jsx
- src/pages/SearchPage/index.jsx
ex) (#17 ) feat/login -> main
1. 페이지네이션 누르면 화면 위쪽으로 가게 수정 
2. map으로 인한 버그 발생 해서 수정계획
> fix: 페이지네이션 수정

- src/pages/DetailPage/components/Detail.jsx
- src/pages/DetailPage/components/WishlistButton.jsx
- src/pages/DetailPage/index.jsx
ex) (#11 ) feat/DetailPage -> Fix
1. 불필요한 주석과 console.log 삭제 했습니다.
2. 버튼이 바로 반응하는지 확인 하기 위해 Hover를 추가했습니다.
> fix: 불필요한 주석, console.log 삭제

- src/pages/CommunityDetailPage/components/CommentDelete.jsx
- src/pages/CommunityDetailPage/components/CommentForm.jsx
- src/pages/CommunityDetailPage/components/FollowButton.jsx
- src/pages/CommunityDetailPage/components/Follower.jsx
- src/pages/CommunityDetailPage/components/LikeButton.jsx
- src/pages/CommunityDetailPage/components/PostDelete.jsx
- src/pages/CommunityDetailPage/components/PostEditModal.jsx
- src/pages/CommunityDetailPage/components/icon/ProfileImage.jsx
- src/pages/CommunityDetailPage/index.jsx
- src/pages/CommunityPage/components/DetailedPosts.jsx
- src/pages/CommunityPage/components/PostForm.jsx
- src/pages/CommunityPage/components/PostFormModal.jsx
- src/pages/CommunityPage/components/PostRender.jsx
- src/pages/CommunityPage/index.jsx
> Etc : 커뮤니티 import 경로 수정

- index.html
> fix : 웹 title 수정

- src/pages/SearchPage/components/DetailCard.jsx
- src/pages/SearchPage/components/DetailMediumCard.jsx
- src/pages/SearchPage/components/DetailSmallCard.jsx
- src/pages/SearchPage/index.jsx
> fix : href 대신 router로 설정

- src/pages/SearchPage/index.jsx
> fix : 파일 경로 수정

- src/redux/slices/wishlist.slice.js
ex) (#93 ) feat/etc -> fix
wishlist.slice 내 경로 수정했습니다.
> [Fix] redux slice 내 경로 수정

- src/pages/SearchPage/index.jsx
ex) (#17) feat/search -> main
파일명 수정했습니다!
> fix : 파일명 수정

- src/pages/MyPage/components/aside/Aside.jsx
- src/pages/MyPage/components/main/comment/CommentSection.jsx
- src/pages/MyPage/components/main/liked/LikedSection.jsx
- src/pages/MyPage/components/main/post/PostsSection.jsx
- src/pages/MyPage/components/main/schedule/ScheduleSection.jsx
- src/pages/MyPage/components/main/scrap/ScrapSection.jsx
- src/pages/MyPage/components/userfollower/followerTab/FollowerItem.jsx
> 마이페이지 경로 수정

- src/pages/Homepage/components/Community/Carousel.jsx
> [FIX] : svg 아이콘 경로 수정

- src/pages/MyPage/components/main/common/NoContent.jsx
- src/pages/MyPage/components/main/schedule/ScheduleSection.jsx
> feat : 마이페이지 빈 일정시 이동 기능 추가

- src/index.css
> refactor : 불필요한 color-scheme 주석처리

- src/pages/AddPlanPage/components/Search.jsx
> refactor : css 삭제
